name: Go Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run go vet
        run: go vet ./...

      - name: Run Table-Driven Tests
        run: go test -v -race ./...

      - name: Run Benchmarks
        run: go test -bench=. ./...
